= API Changes =

== Deprecate IPasswordStore ==

The `org.dogtagpki.jss.tomcat.IPasswordStore` has been deprecated.
Use `org.dogtagpki.jss.tomcat.PasswordStore` instead.

== SSLSocket Changes ==

The `org.mozilla.jss.ssl.SSLSocket` has been modified to extend `javax.net.ssl.SSLSocket`.

== JSSSocket Changes ==

The `org.mozilla.jss.ssl.javax.JSSSocket` has been modified to extend `org.mozilla.jss.ssl.SSLSocket`.

== SSLCertificateApprovalCallback Changes ==

The `approve()` method in `org.mozilla.jss.ssl.SSLCertificateApprovalCallback` has been modified
to accept `java.security.cert.X509Certificate` instead of `org.mozilla.jss.crypto.X509Certificate`.

== CryptoManager Changes ==

The `importCertToPerm()` method in `org.mozilla.jss.CryptoManager` has been modified
to return `org.mozilla.jss.crypto.X509Certificate`.

== CryptoManager Changes ==

The `importCertToPerm()` method in `org.mozilla.jss.CryptoManager` has been modified
to return `org.mozilla.jss.crypto.X509Certificate`.

== Remove PK11InternalCert and PK11InternalTokenCert ==

The `org.mozilla.jss.pkcs11.PK11InternalCert` and `org.mozilla.jss.pkcs11.PK11InternalTokenCert`
are no longer used so they have been removed.
