= API Changes =

== Remove org.mozilla.jss.pkcs11.PK11TokenCert ==

The `org.mozilla.jss.pkcs11.PK11TokenCert` class is not used so it has been removed.

== Deprecate org.mozilla.jss.pkcs11.PK11InternalTokenCert ==

The `org.mozilla.jss.pkcs11.PK11InternalTokenCert` class has been deprecated and will be removed in the future.
Use `org.mozilla.jss.pkcs11.PK11Cert` instead.

== Deprecate org.mozilla.jss.pkcs11.PK11InternalCert ==

The `org.mozilla.jss.pkcs11.PK11InternalCert` class has been deprecated and will be removed in the future.
Use `org.mozilla.jss.pkcs11.PK11Cert` instead.

== Consolidate trust flag constants ==

The trust flag constants defined in `org.mozilla.jss.netscape.security.pkcs.PKCS12` and `org.mozilla.jss.crypto.InternalCertificate` have been deprecated.
Use the corresponding constants in `org.mozilla.jss.pkcs11.PK11Cert` instead.

|===
| `PKCS12` | `InternalCertificate` | `PK11Cert`

| `TERMINAL_RECORD`
| `VALID_PEER`
| `VALID_PEER`

| `TRUSTED`
| `TRUSTED_PEER`
| `TRUSTED_PEER`

| `SEND_WARN`
|
| `SEND_WARN`

| `VALID_CA`
| `VALID_CA`
| `VALID_CA`

| `TRUSTED_CA`
| `TRUSTED_CA`
| `TRUSTED_CA`

| `NS_TRUSTED_CA`
|
| `NS_TRUSTED_CA`

| `USER`
| `USER`
| `USER`

| `TRUSTED_CLIENT_CA`
| `TRUSTED_CLIENT_CA`
| `TRUSTED_CLIENT_CA`

| `INVISIBLE_CA`
|
| `INVISIBLE_CA`

| `GOVT_APPROVED_CA`
|
| `GOVT_APPROVED_CA`
|===

== Consolidate trust flag methods ==

The trust flag methods in `org.mozilla.jss.netscape.security.pkcs.PKCS12` have been deprecated.
Use the corresponding methods in `org.mozilla.jss.pkcs11.PK11Cert` instead.

|===
| `PKCS12` | `PK11Cert`

| `isFlagEnabled()`
| `isTrustFlagEnabled()`

| `encodeFlags()`
| `encodeTrustFlags()`

| `decodeFlags()`
| `decodeTrustFlags()`
|===

The trust flag methods in `org.mozilla.jss.netscape.security.pkcs.PKCS12Util` have been deprecated.
Use the corresponding methods in `org.mozilla.jss.pkcs11.PK11Cert` instead.

|===
| `PKCS12Util` | `PK11Cert`

| `getTrustFlags()`
| `getTrustFlags()`

| `setTrustFlags()`
| `setTrustFlags()`
|===

== Add symkey library ==

The PKI symkey library has been moved into JSS with the following changes:

- the package name has been renamed to `org.mozilla.jss.symkey`
- the JAR file has been renamed to `jss-symkey.jar`
- the shared library file has been renamed to `libjss-symkey.so`
