name: Required Tests for v4.4.x branch

on: [push, pull_request]

jobs:
  fedora31:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@v2
    - name: Build and Run the Docker Image
      run: bash tools/run_container.sh "fedora_31"
  centos7:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@v2
    - name: Build and Run the Docker Image
      run: bash tools/run_container.sh "centos_7"
